gateways:
  ws:
    type: websocket
    port: 9016
    url: ws://chatroom.lqsl.cloud
transports:
  main:
    type: memory
stores:
  main:
    type: memory
    limit: 1000
    snapshotThreshold: 10
scopes:
  security:
    jwt:
      signkey: DWHh@Y@23eh2HG@#GE@#YTE@#E@#EHJG@#FEH@#FE@#
      issuer: chatroom.lqsl.cloud
      audience: chatroom-app
      duration: 1 day
